INSERT INTO appl_auth.organizations (organization_name,webapp_name,country_name,hashed_password,industry,keyspace_name,username) VALUES (
'dod','URM','United States','7579659330','Public','dod','dod');
INSERT INTO appl_auth.organizations (organization_name,webapp_name,country_name,hashed_password,industry,keyspace_name,username) VALUES (
'vmasc','URM','United States','7575551212','Education','vmasc','vmasc');
INSERT INTO appl_auth.organizations (organization_name,webapp_name,country_name,hashed_password,industry,keyspace_name,username) VALUES (
'g2 ops','URM','United States','7579659330','Technology','g2','g2');
