--------------------------------------------Gynecology------------------------------------
--10.106.245.10
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:009293e0-1b64-440e-bda0-61fcffa2a1ab}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=1687ed09-a996-4247-928c-99c64c3d7f9c;
----------------------------------------------Plastic Surgery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.63.74
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:b7db607d-6338-4946-a050-07d9a5b80a23}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=bfed2e40-c9d2-4d06-8cb8-4d5e77940079;

----------------------------------------------Orthopedic Surgery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.57.228
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:54cec801-9260-43e1-80e1-4161a9c39f33}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=2d027593-99d2-47b0-98fb-416a2df18bdf;

----------------------------------------------Lab 1-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.246.133
--10.106.246.132
update g2.business_value_attribution set 
runs_on_hosts = {
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:68d6422e-5535-4685-a117-5baae9af76c2},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:5e4e758d-d44e-4229-b037-3c1ce7d05fec}
}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=7258e248-a560-4947-b1ad-cbdb58fd0be9;
----------------------------------------------Neonatology-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.60.105
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:3326e3dd-7498-48b2-aeba-5c720e8e0c94}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=1892f9f4-e1a6-4803-a09e-896aa7736934;

----------------------------------------------Dental-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.74.29
--10.106.248.248
update g2.business_value_attribution set 
runs_on_hosts = {
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:3e3a94c4-925f-46d7-abf6-850f46862626},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:16ffe5e7-7e27-4dec-a8a2-0a99a6f052f2}
}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=8c51ab57-c2d1-4ae6-b8b5-c0112456f471;
----------------------------------------------Oncology Surgery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.62.241
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:f3703bcb-2388-4c7c-a693-5a0b4a5fc44b}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=a52de7bb-10d9-48bb-8776-4b6734c54796;
----------------------------------------------Obstetrics/Delivery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.253.68
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:bbe51d61-5660-49af-9983-23359e8842fe}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=fc475e09-3710-4e96-a98d-3d166c2ad902;
----------------------------------------------General Surgery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.75.189
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:8598d4fa-b3c9-4442-a752-c048152b9153}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=6ee4f1ae-7357-43ae-9b92-3b60c19e99e9;
----------------------------------------------Normal Newborns-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.61.233
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:aaac5cea-1da3-4343-9b96-3e544154da21}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=3a2f7aba-4b0d-4e7c-b802-93fa661a5acf;
----------------------------------------------Admissions-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.120.8.214
--10.120.9.44
--10.120.9.35
--10.120.9.68
--10.120.9.118
--10.120.10.20
--10.120.9.23
--10.120.8.236
--10.120.9.36
--10.120.9.8
--10.120.9.65
--10.120.9.3
--10.120.8.213
--10.120.8.240

update g2.business_value_attribution set 
runs_on_hosts = {
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:f71b583b-5616-415c-85e9-f17b4d0f74e1},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:fdbd0a74-9bd1-4152-bbb4-7c57ae1930e5},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:9d35c107-4260-49a4-9176-d94546b62a21},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:51bf5e4d-441d-417b-9c89-8d2ef4b51411},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:09642bda-b24c-406c-9a57-433259ca4550},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:29cd585a-f585-4673-8cff-f3bcfc0d64d2},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:e17c3e13-9872-435e-839d-0cb6a02d187b},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:3f1fa582-59b4-44e3-a13c-95e20f0877da},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:aa4926e5-c1d6-4d2c-8161-264bc8ba7192},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:d40e8867-6734-4025-9f0a-18095a370318},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:6aa04005-a4ba-4480-8eef-bf41f9c48936},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:7ac52bf9-7917-4740-beec-30a2a839985e},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:69d5e928-07e4-416c-8bd4-cd80f58a9a65},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:9a286eab-e7dd-4da7-931d-256d3931c913}
}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=5d9ca1ff-67d3-41cb-ad7a-98ecb0d7a4f9;
----------------------------------------------Opthamology-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.74.52
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:68d3581b-6086-4544-97ee-73ff015a14fa}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=b1e19428-917e-448e-8a1a-4f7bb37f3e3b;
----------------------------------------------Oncology-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.74.250
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:cc88fa6d-4009-4b79-8892-cd2584c736a2}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=6d3183dd-b150-4a62-9e37-86d3b8a4782d;
----------------------------------------------General Medicine-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.75.208
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:8ff02d65-af78-4e9e-9060-434512b22c0d}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=61608307-07f9-4455-9b80-4be58972e0fb;
----------------------------------------------Infectious Diseases-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.74.12
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:8cf2c2e7-dae0-495f-aa66-70d239872638}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=d2f7a916-d258-4480-b3e3-5764935817a8;
----------------------------------------------Trauma, Multiple-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.75.243
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:97d021eb-be77-4d6c-90bf-1a43ff60595b}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=815b1ad3-4065-48b3-9d85-dbc9f74e08f5;
----------------------------------------------Psychiatry-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.61.243
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:3f0f780e-00a4-42dc-84d4-5857b26c4e97}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=0cbc2726-f346-4912-8c05-7984a657e0d8;
----------------------------------------------Emergency Room-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.120.9.202
--10.120.9.20
--10.120.8.234
--10.120.9.7
--10.120.9.18
--10.120.9.194
--10.120.9.201
--10.120.9.22
--10.120.8.223
--10.120.8.219
--10.120.9.15
--10.120.9.189
--10.120.9.193
--10.120.9.86

update g2.business_value_attribution set 
runs_on_hosts = {
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:9e5db848-1367-436c-8b65-cb5897d0a502},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:94c13176-adc6-4589-90ab-961484f21ca7},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:f8c9448b-8ded-42cf-81b6-0b8d8fa7d92f},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:aff54fef-59de-449f-9eff-d959cf0b67c8},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:9c2dd221-0360-4e1f-9421-121c2a64fd30},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:b5a51646-810f-46cf-8fb4-66377e974ee6},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:dd0541f9-231a-43ed-9830-24d2094faae1},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:a895318d-2344-441d-90db-b1eefd31c735},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:2afaa05e-3457-45ec-82c4-fa1828f402f3},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:a032eedd-fb68-4ba1-924e-4d1bd09e9317},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:c5da84f7-fdb2-4070-be2b-557672166bbe},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:3ce3e439-1cb8-43b5-97d3-97240ebe2f7d},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:2df7aba9-a124-4a29-a104-9b21e0eb8d58},
{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.120',internal_system_id:2ec1a1e1-13a9-4442-9e37-254044d3c5ff}
}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=ca452a44-bd19-40a7-bf10-a560a274f5a4;
----------------------------------------------Open Heart Surgery-------------------------------------------------------------------------------------------------------------------------------------------------------
--10.106.75.204
update g2.business_value_attribution set 
runs_on_hosts = {{site_id:96a3378e-2f67-4b9d-ab67-9ee9d533b88f,ip_subnet_or_building:'10.106',internal_system_id:8ab0afa6-33b8-45ba-aa9b-87fd40436860}}
where site_id=96a3378e-2f67-4b9d-ab67-9ee9d533b88f and business_process_id=a88e4b51-6b2d-4623-a4cb-48b980d03e98;